### ISSUE TITLE
Text color on selected app/item can be improved

### ISSUE THREAD

**Issue by palaniraja** [macmade/CrashReports#1]
Thank you for open sourcing the app.

Selected item, background/text color on sidebar is not legible, I thought it is due to Reduce transparency setting, seems it could use some help with nicer color in the screenshot in readme.

![screen shot 2017-03-05 at 1 54 44 pm](https://cloud.githubusercontent.com/assets/124864/23585723/9a4429e4-01ab-11e7-8091-b9cf51e14a6c.png)

**Comment by macmade** [comment]
Thanks : )

Should be slightly better in 1.2:  
https://github.com/macmade/Diagnostics/releases/tag/1.2
